%YAML:1.0
# data
data_dir: /home/cadit/Data/office3_clean/
association_dir: /home/cadit/Data/office3_clean/associations.txt
voc_dir: /home/cadit/RGBD-SLAM/Vocabulary/vocab_office_3.yml.gz
gt_dir: /home/cadit/RGBD-SLAM/GT/office3_gt.txt
est_dir: /home/cadit/Result_RGBD/045/stamped_traj_estimate.txt
# camera intrinsics
camera.fx: 481.2
camera.fy: -480.0
camera.cx: 319.5
camera.cy: 239.5

stride: 1

height: 480
width: 640

loop_detect: 1
score_threshold: 0.35

# feature
feature_type: ORB
num_features: 500
num_features_tracking_threshold: 300
depth_min: 0.5
depth_max: 10.0



match_threshold_tracking: 20
loop_frame_th: 200

knn_ratio: 0.7

window_size: 5
keyframe_min_dist_threshold: 0.05

pixel_to_meter_scalefactor: 0.001
