%YAML:1.0
# data
data_dir: /home/cadit/Data/rgbd_dataset_freiburg2_desk/
association_dir: /home/cadit/Data/rgbd_dataset_freiburg2_desk/associations.txt
voc_dir: /home/cadit/Research/RGBD_SLAM/Vocabulary/vocab_f2_desk.yml.gz
gt_dir: None
est_dir: /home/cadit/Result_RGBD/f2_desk_05_2/stamped_traj_estimate.txt
# camera intrinsics
camera.fx: 525.0
camera.fy: 525.0
camera.cx: 319.5
camera.cy: 239.5

stride: 1

height: 480
width: 640

loop_detect: 1
score_threshold: 0.3
rel_pose_thresh: 0.5

# feature
feature_type: ORB
num_features: 1000
num_features_tracking_threshold: 500
depth_min: 0.2
depth_max: 3.0



match_threshold_tracking: 20
loop_frame_th: 100

knn_ratio: 0.7

window_size: 10
keyframe_min_dist_threshold: 0.01

pixel_to_meter_scalefactor: 0.0002
